;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
	kill-region
	ns-copy-including-secondary
	sgml-close-tag
	sgml-close-tag-back
	view-order-manuals
	))

(setq mc/cmds-to-run-once
      '(
	backward-sentence
	backward-sexp
	browse-url-of-buffer
	electric-newline-and-maybe-indent
	handle-switch-frame
	js2-mode-show-node
	sgml-slash
	web-beautify-html
	web-beautify-js
	))
