;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
	ns-copy-including-secondary
	sgml-close-tag
	view-order-manuals
	))

(setq mc/cmds-to-run-once
      '(
	browse-url-of-buffer
	electric-newline-and-maybe-indent
	sgml-slash
	))
